version: "2"

services:
  charmpool:
    container_name: "charmpool"
    extends:
      file: "../docker-compose-base.yml"
      service: "_base"
    image: "elastisys/charmpool:{{ tag }}"
    environment:
      - "CHARMPOOL_API_ENDPOINT={{ juju_api_endpoint }}"
      - "CHARMPOOL_MODEL_UUID={{ juju_model_uuid }}"
      - "CHARMPOOL_USERNAME={{ juju_username }}"
      - "CHARMPOOL_PASSWORD={{ juju_password }}"
      - "CHARMPOOL_APPLICATION={{ application }}"
      - "CHARMPOOL_PORT=80"
      - "CHARMPOOL_REFRESH_INTERVAL={{ juju_refresh_interval }}"
